export const cities = [
  {name: 'Los Angeles', id: 1},
  {name: 'Philadelphia', id: 2},
  {name: 'Chicago', id: 3},
  {name: 'Washington DC', id: 4},
  {name: 'New York', id: 5},
  {name: 'San Diego', id: 6},
  {name: 'Fort Worth', id: 7},
  {name: 'Houston', id: 8},
  {name: 'Cleveland', id: 9},
  {name: 'Pittsburg', id: 10},
  {name: 'Detroit', id: 11},
  {name: 'Jacksonville', id: 12},
  {name: 'Denver', id: 13},
  {name: 'Columbus', id: 14},
  {name: 'El Paso', id: 15},
  {name: 'New Orleans', id: 16},
  {name: 'Cincinnati', id: 17},
  {name: 'Nashville', id: 18},
  {name: 'Miami', id: 19},
  {name: 'Tampa', id: 20},
  {name: 'Bakersfield', id: 22},
  {name: 'Tuscon', id: 23},
  {name: 'Baltimore', id: 25},
  {name: 'St Louis', id: 26},
  {name: 'Las Vegas', id: 27},
  {name: 'Memphis', id: 28},
  {name: 'Seatle', id: 29},
  {name: 'San Fransisco', id: 30},
];
